# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegoProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('product_code', models.IntegerField()),
                ('piece_count', models.IntegerField()),
                ('datetime_updated', models.DateTimeField(auto_now_add=True, verbose_name='datetime updated')),
            ],
        ),
        migrations.CreateModel(
            name='LegoProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField()),
                ('lego_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LegoProduct')),
            ],
        ),
        migrations.CreateModel(
            name='LegoProductSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('sku_number', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('product_url', models.TextField()),
                ('datetime_updated', models.DateTimeField(auto_now_add=True, verbose_name='datetime updated')),
                ('lego_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LegoProduct')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='legoproductsku',
            unique_together=set([('lego_product', 'site', 'sku_number')]),
        ),
    ]
