# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-29 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoproduct',
            name='product_code',
            field=models.IntegerField(db_index=True),
        ),
    ]
